<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Find jobs</name>
   <tag></tag>
   <elementGuidId>2b92b2cc-edf8-42aa-a183-cd0c359d1ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.yosegi-InlineWhatWhere-primaryButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>272f3411-d4ac-40e1-9221-5f4f7955186f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yosegi-InlineWhatWhere-primaryButton</value>
      <webElementGuid>534ce607-96b2-4521-9884-97997a0275f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ca1ba2ec-5f91-4116-9fb9-baa8802753b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find jobs</value>
      <webElementGuid>61c9b1ab-545f-4dfa-a0cd-0f854733261e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobsearch&quot;)/button[@class=&quot;yosegi-InlineWhatWhere-primaryButton&quot;]</value>
      <webElementGuid>8ac537d3-7383-487d-975b-27f93bfc6b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>d54ab490-45c9-43b7-af6b-a330fdf98949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='jobsearch']/button</value>
      <webElementGuid>67fb1f4b-28c1-4f47-a6b6-96bff9fc5ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where'])[1]/following::button[1]</value>
      <webElementGuid>7b5cb0b1-7e67-4bd9-8e8a-666bb09a0b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What'])[1]/following::button[1]</value>
      <webElementGuid>60351d05-6c6b-4783-bfce-ee9f842d6254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post your resume'])[1]/preceding::button[1]</value>
      <webElementGuid>1b4ffabc-c977-40d7-8a52-b1b7c5072add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[1]/preceding::button[1]</value>
      <webElementGuid>74450187-2b52-4c2d-9bf4-75336d2f54ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>6c10369d-0f0e-43a3-b7e6-f2582e53f701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Find jobs' or . = 'Find jobs')]</value>
      <webElementGuid>d2d372f5-6789-4661-821b-a755483434e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
