<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What_q</name>
   <tag></tag>
   <elementGuidId>34c9a130-f897-4357-aa28-89de84867003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-input-what</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-input-what']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f17307b-4007-44b1-a339-b16501c62725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdf67899-d229-4e7e-a70e-79382306c6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label-text-input-what</value>
      <webElementGuid>659d265f-5584-41c8-944f-9d4736f9b63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-input-what</value>
      <webElementGuid>891205c4-3712-4a69-9676-ff72f639f8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>64d975c0-76d6-4fe0-a313-deb02397f04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job title, keywords, or company</value>
      <webElementGuid>1ceba894-ac4b-4fbf-9c1b-373885dea781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b52bfc5e-caf8-4513-b81f-3f3aa127181e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>text-input-what-suggestion-list</value>
      <webElementGuid>c3fa50b9-8521-479b-a935-6813ac4e56a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icl-TextInput-control icl-TextInput-control--withIconRight focus-visible</value>
      <webElementGuid>48c84b06-fead-469e-b87f-99b99f1cddde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d7e65e1-5603-47cd-917e-fe5ceb752a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-input-what&quot;)</value>
      <webElementGuid>a3621eb7-a0e2-49a1-9761-f81256945527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-input-what']</value>
      <webElementGuid>2f7eab8d-8158-470c-9144-9564f2e93bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='jobsearch']/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>36f1a05c-1bb1-44e4-b7ea-5a76576e1d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d77063f6-ef6c-4197-b744-a9e9efb0c0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text-input-what' and @name = 'q' and @placeholder = 'Job title, keywords, or company']</value>
      <webElementGuid>c45ee1ec-91a0-4a97-885b-fc41ad77ad81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
